### ISSUE TITLE
link and the  proc ::tclfpdf::_putpage

### ISSUE THREAD

**Issue by gregnix** [lamuzzachiodi/tclfpdf#3]
something is missing:
variable links

DefPageSize is not an array but a list and the expr is false:
set h1 [ expr DefOrientation == "p" ? $DefPageSize(1)*$k : $DefPageSize(0)*$k];
set h1 [ expr { $DefOrientation == "P" ? [lindex $DefPageSize 1 ]*$k : [lindex  $DefPageSize 0 ]*$k }] ;

error lassing instead of lassig:
lassing $links($pl(4)) l(0) l(1);
lassign $links($pl(4)) l(0) l(1);

**Comment by lamuzzachiodi** [comment]
Fix in 1.6
