### ISSUE TITLE
Problems with some Gif and Png files

### ISSUE THREAD

**Issue by mittelmark** [lamuzzachiodi/tclfpdf#6]
There was a discussion on comp.lang.tcl that some type of png or gif files (interlaced) make problems. There were a workaround suggested to convert to jpeg and then import this file instead. May be you can have a check of the problem yourself:

https://groups.google.com/g/comp.lang.tcl/c/uxA-hdvntOI

I added a Wiki entry as well to show the workaround:

https://wiki.tcl-lang.org/page/TCLFPDF?V=10

Detlef

**Comment by lamuzzachiodi** [comment]
I´ll take a look. 
Thanks you for you comment.

**Comment by lamuzzachiodi** [comment]
At least for me, that workaround doesn't work at all. In other hand, jpg isn't supported by image photo, only GIF and PNG (tcl 8.6.X). So, convert GIF to PNG still is the most reliable workaround.
